{% set name = "nionswift-io" %}
{% set version = "15.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d40696c8802d67c348eed69bb6882f088b99f9adefc53c1c26701eca725c1d18

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - niondata >=15.6,<16.0
    - nionutils >=0.4.0,<5.0.0
    - numpy >=1.25,<2.0
    - python >=3.9

test:
  imports:
    - nionswift_plugin.DM_IO
    - nionswift_plugin.DM_IO.test
    - nionswift_plugin.TIFF_IO
    - nionswift_plugin.TIFF_IO.test
  requires:
    - h5py

about:
  home: https://github.com/nion-software/nionswift-io
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: IO handlers for NionSwift.
  dev_url: https://github.com/nion-software/nionswift-io

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
