{% set name = "nionswift-io" %}
{% set version = "15.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 691373ef0349b480f5ab0f8b24c9ef85a0cce824980257d558f70806f62f182c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - niondata >=0.14.0,<0.16.0
    - nionutils >=0.4.0,<0.5.0
    - numpy >=1.21,<2.0
    - python >=3.8

test:
  imports:
    - nionswift_plugin.DM_IO
    - nionswift_plugin.DM_IO.test
    - nionswift_plugin.TIFF_IO
    - nionswift_plugin.TIFF_IO.test
  requires:
    - h5py

about:
  home: https://github.com/nion-software/nionswift-io
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: IO handlers for NionSwift.
  dev_url: https://github.com/nion-software/nionswift-io

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
