{% set name = "nionswift-io" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49da8bff9200a0a5da183cfc594218a9588b1041b262fb8842dac33e45124b35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - nionutils >=0.3.10
    - niondata >=0.13.1
    - numpy
    - python >=3.7

test:
  imports:
    - nionswift_plugin.DM_IO
    - nionswift_plugin.DM_IO.test
    - nionswift_plugin.TIFF_IO
    - nionswift_plugin.TIFF_IO.test
  requires:
    - h5py

about:
  home: https://github.com/nion-software/nionswift-io
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: IO handlers for NionSwift.
  dev_url: https://github.com/nion-software/nionswift-io

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
